// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1d30CZ9kAUBToce7SLJCub1a7RQs0YOY',
    appId: '1:764684738213:web:73d67fe26b90034301374c',
    messagingSenderId: '764684738213',
    projectId: 'errorfit-dev-b8930',
    authDomain: 'errorfit-dev-b8930.firebaseapp.com',
    storageBucket: 'errorfit-dev-b8930.firebasestorage.app',
    measurementId: 'G-G046VK6P19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnWw_TjRNZ1rVxkodm8K6iRZHJ7b9_d6I',
    appId: '1:764684738213:android:59b050b2fb4c08cd01374c',
    messagingSenderId: '764684738213',
    projectId: 'errorfit-dev-b8930',
    storageBucket: 'errorfit-dev-b8930.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzemw8pRV-InS3fEHoK81n7FwkBX1oFP8',
    appId: '1:764684738213:ios:9054ad63c428b2cd01374c',
    messagingSenderId: '764684738213',
    projectId: 'errorfit-dev-b8930',
    storageBucket: 'errorfit-dev-b8930.firebasestorage.app',
    androidClientId: '764684738213-kni18icr9eb6jg9784gidnr60oovfkgb.apps.googleusercontent.com',
    iosClientId: '764684738213-8mko11a4kavq94ubgnv5in4ommgqoe9s.apps.googleusercontent.com',
    iosBundleId: 'com.codesignificant.errorfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzemw8pRV-InS3fEHoK81n7FwkBX1oFP8',
    appId: '1:764684738213:ios:9054ad63c428b2cd01374c',
    messagingSenderId: '764684738213',
    projectId: 'errorfit-dev-b8930',
    storageBucket: 'errorfit-dev-b8930.firebasestorage.app',
    androidClientId: '764684738213-kni18icr9eb6jg9784gidnr60oovfkgb.apps.googleusercontent.com',
    iosClientId: '764684738213-8mko11a4kavq94ubgnv5in4ommgqoe9s.apps.googleusercontent.com',
    iosBundleId: 'com.codesignificant.errorfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1d30CZ9kAUBToce7SLJCub1a7RQs0YOY',
    appId: '1:764684738213:web:b2a8b9abed050d3901374c',
    messagingSenderId: '764684738213',
    projectId: 'errorfit-dev-b8930',
    authDomain: 'errorfit-dev-b8930.firebaseapp.com',
    storageBucket: 'errorfit-dev-b8930.firebasestorage.app',
    measurementId: 'G-2NCRMH3YCX',
  );
}
