name: Deploy Flutter Web to Hostinger

on:
  push:
    branches:
      - dev  # Trigger on pushes to the dev branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter web
        run: flutter build web --release

      - name: Deploy to Hostinger via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          port: ${{ secrets.HOSTINGER_PORT }}
          source: "build/web/*"
          target: "/home/u557234092/domains/4ss.in/public_html/PipeLine"
